### PR TITLE
Flexible status

### LINKED ISSUE #17: Status is "undefined"
Packages which were shipped today show `undefined`; appears to be happening in this code:

    var headerStatus = parcelStatustext[parcelStatus.indexOf(p.status)];

...where `p.status` is "InfoReceived".  Since that's not in `parcelStatus`, it fails.  I assume it's equivalent to "pending".

### PR DESCRIPTION
**Pull request by MikeBishop**
Enables multiple possible strings to map to a single status index, since I'm guessing the value of this string can vary between couriers.

Fixes #17.

### CODE REVIEW

**Comment by martinkooij** [comment]
thanks for the help, will incorporate soon. I am by a cident busy cleaning the code the next few days. This would be a good improvement. 

Do you have (with debug: true in the config file) a dump from the console for me. I also want to analyse the  times and possoble timezones that are forwarded depending on courier. 


⁣BlueMail voor Android downloaden ​

Op 26 jan. 2021 22:25, om 22:25, Mike Bishop <notifications@github.com> schreef:

**Comment by MikeBishop** [comment]
[2021-01-26 16:55:03.126] [LOG]    [DEBUG] Notification received CONFIG
[2021-01-26 16:55:03.135] [LOG]    [DEBUG] Notification received INTERVAL_SET
[2021-01-26 16:55:03.136] [LOG]    [DEBUG] Notification received TRACKTRY_FETCHER
[2021-01-26 16:55:03.523] [LOG]    RESULT.DATA-NoT =  {
  "items": [
    {
      "id": "--REDACTED--",
      "tracking_number": "--REDACTED--",
      "carrier_code": "ups",
      "status": "InfoReceived",
      "created_at": "2021-01-26T20:43:11+00:00",
      "updated_at": "2021-01-26T20:47:03+00:00",
      "order_create_time": null,
      "customer_email": "",
      "title": "Computer Internals",
      "order_id": null,
      "comment": null,
      "customer_name": null,
      "archived": false,
      "original_country": "",
      "itemTimeLength": null,
      "stayTimeLength": 1,
      "service_code": null,
      "status_info": null,
      "origin_info": {
        "ReferenceNumber": null,
        "ItemReceived": null,
        "ItemDispatched": null,
        "DepartfromAirport": null,
        "ArrivalfromAbroad": null,
        "CustomsClearance": null,
        "DestinationArrived": null,
        "weblink": "https://www.ups.com/us/en/Home.page",
        "phone": null,
        "carrier_code": "ups",
        "trackinfo": [
          {
            "Date": "2021-01-26 13:44",
            "StatusDescription": "Shipper created a label, UPS has not received the package yet.",
            "Details": "US",
            "ActType": "M",
            "substatus_num": 11,
            "substatus": "notfound001",
            "checkpoint_status": "transit"
          }
        ]
      },
      "destination_info": {
        "ItemReceived": null,
        "ItemDispatched": null,
        "DepartfromAirport": null,
        "ArrivalfromAbroad": null,
        "CustomsClearance": null,
        "DestinationArrived": null,
        "weblink": null,
        "phone": null,
        "carrier_code": null,
        "trackinfo": null
      },
      "lastEvent": "Shipper created a label, UPS has not received the package yet.,US,2021-01-26 13:44",
      "lastUpdateTime": "2021-01-26 13:44"
    },
    {
      "id": "--REDACTED--",
      "tracking_number": "--REDACTED--",
      "carrier_code": "ups",
      "status": "InfoReceived",
      "created_at": "2021-01-26T20:42:43+00:00",
      "updated_at": "2021-01-26T20:42:48+00:00",
      "order_create_time": null,
      "customer_email": "",
      "title": "Computer WiFi/BT",
      "order_id": null,
      "comment": null,
      "customer_name": null,
      "archived": false,
      "original_country": "",
      "itemTimeLength": null,
      "stayTimeLength": 1,
      "service_code": null,
      "status_info": null,
      "origin_info": {
        "ReferenceNumber": null,
        "ItemReceived": null,
        "ItemDispatched": null,
        "DepartfromAirport": null,
        "ArrivalfromAbroad": null,
        "CustomsClearance": null,
        "DestinationArrived": null,
        "weblink": "https://www.ups.com/us/en/Home.page",
        "phone": null,
        "carrier_code": "ups",
        "trackinfo": [
          {
            "Date": "2021-01-26 10:28",
            "StatusDescription": "Shipper created a label, UPS has not received the package yet.",
            "Details": "US",
            "ActType": "M",
            "substatus_num": 11,
            "substatus": "notfound001",
            "checkpoint_status": "transit"
          }
        ]
      },
      "destination_info": {
        "ItemReceived": null,
        "ItemDispatched": null,
        "DepartfromAirport": null,
        "ArrivalfromAbroad": null,
        "CustomsClearance": null,
        "DestinationArrived": null,
        "weblink": null,
        "phone": null,
        "carrier_code": null,
        "trackinfo": null
      },
      "lastEvent": "Shipper created a label, UPS has not received the package yet.,US,2021-01-26 10:28",
      "lastUpdateTime": "2021-01-26 10:28"
    },
    {
      "id": "--REDACTED--",
      "tracking_number": "--REDACTED--",
      "carrier_code": "ups",
      "status": "InfoReceived",
      "created_at": "2021-01-26T20:26:20+00:00",
      "updated_at": "2021-01-26T20:26:29+00:00",
      "order_create_time": null,
      "customer_email": "",
      "title": "Computer Case",
      "order_id": null,
      "comment": null,
      "customer_name": "Computer Case",
      "archived": false,
      "original_country": "",
      "itemTimeLength": null,
      "stayTimeLength": 1,
      "service_code": null,
      "status_info": null,
      "origin_info": {
        "ReferenceNumber": null,
        "ItemReceived": null,
        "ItemDispatched": null,
        "DepartfromAirport": null,
        "ArrivalfromAbroad": null,
        "CustomsClearance": null,
        "DestinationArrived": null,
        "weblink": "https://www.ups.com/us/en/Home.page",
        "phone": null,
        "carrier_code": "ups",
        "trackinfo": [
          {
            "Date": "2021-01-26 10:28",
            "StatusDescription": "Shipper created a label, UPS has not received the package yet.",
            "Details": "US",
            "ActType": "M",
            "substatus_num": 11,
            "substatus": "notfound001",
            "checkpoint_status": "transit"
          }
        ]
      },
      "destination_info": {
        "ItemReceived": null,
        "ItemDispatched": null,
        "DepartfromAirport": null,
        "ArrivalfromAbroad": null,
        "CustomsClearance": null,
        "DestinationArrived": null,
        "weblink": null,
        "phone": null,
        "carrier_code": null,
        "trackinfo": null
      },
      "lastEvent": "Shipper created a label, UPS has not received the package yet.,US,2021-01-26 10:28",
      "lastUpdateTime": "2021-01-26 10:28"
    }
  ]
}
[2021-01-26 16:55:08.663] [LOG]    [DEBUG] Notification received PARCELLISTLENGTH:
[2021-01-26 16:55:08.663] [LOG]    OOPS.  PARCELLISTLENGTH: 3
[2021-01-26 16:55:08.676] [LOG]    [DEBUG] Notification received PACKAGE:
[2021-01-26 16:55:08.677] [LOG]    OOPS.  PACKAGE:  {"id":"--REDACTED--","tracking_number":"--REDACTED--","carrier_code":"ups","status":"InfoReceived","created_at":"2021-01-26T20:43:11+00:00","updated_at":"2021-01-26T20:47:03+00:00","order_create_time":null,"customer_email":"","title":"Computer Internals","order_id":null,"comment":null,"customer_name":null,"archived":false,"original_country":"","itemTimeLength":null,"stayTimeLength":1,"service_code":null,"status_info":null,"origin_info":{"ReferenceNumber":null,"ItemReceived":null,"ItemDispatched":null,"DepartfromAirport":null,"ArrivalfromAbroad":null,"CustomsClearance":null,"DestinationArrived":null,"weblink":"https://www.ups.com/us/en/Home.page","phone":null,"carrier_code":"ups","trackinfo":[{"Date":"2021-01-26 13:44","StatusDescription":"Shipper created a label, UPS has not received the package yet.","Details":"US","ActType":"M","substatus_num":11,"substatus":"notfound001","checkpoint_status":"transit"}]},"destination_info":{"ItemReceived":null,"ItemDispatched":null,"DepartfromAirport":null,"ArrivalfromAbroad":null,"CustomsClearance":null,"DestinationArrived":null,"weblink":null,"phone":null,"carrier_code":null,"trackinfo":null},"lastEvent":"Shipper created a label, UPS has not received the package yet.,US,2021-01-26 13:44","lastUpdateTime":"2021-01-26 13:44"}
[2021-01-26 16:55:08.679] [LOG]    [DEBUG] Notification received PACKAGE:
[2021-01-26 16:55:08.680] [LOG]    OOPS.  PACKAGE:  {"id":"--REDACTED--","tracking_number":"--REDACTED--","carrier_code":"ups","status":"InfoReceived","created_at":"2021-01-26T20:42:43+00:00","updated_at":"2021-01-26T20:42:48+00:00","order_create_time":null,"customer_email":"","title":"Computer WiFi/BT","order_id":null,"comment":null,"customer_name":null,"archived":false,"original_country":"","itemTimeLength":null,"stayTimeLength":1,"service_code":null,"status_info":null,"origin_info":{"ReferenceNumber":null,"ItemReceived":null,"ItemDispatched":null,"DepartfromAirport":null,"ArrivalfromAbroad":null,"CustomsClearance":null,"DestinationArrived":null,"weblink":"https://www.ups.com/us/en/Home.page","phone":null,"carrier_code":"ups","trackinfo":[{"Date":"2021-01-26 10:28","StatusDescription":"Shipper created a label, UPS has not received the package yet.","Details":"US","ActType":"M","substatus_num":11,"substatus":"notfound001","checkpoint_status":"transit"}]},"destination_info":{"ItemReceived":null,"ItemDispatched":null,"DepartfromAirport":null,"ArrivalfromAbroad":null,"CustomsClearance":null,"DestinationArrived":null,"weblink":null,"phone":null,"carrier_code":null,"trackinfo":null},"lastEvent":"Shipper created a label, UPS has not received the package yet.,US,2021-01-26 10:28","lastUpdateTime":"2021-01-26 10:28"}
[2021-01-26 16:55:08.681] [LOG]    [DEBUG] Notification received PACKAGE:
[2021-01-26 16:55:08.682] [LOG]    OOPS.  PACKAGE:  {"id":"--REDACTED--","tracking_number":"--REDACTED--","carrier_code":"ups","status":"InfoReceived","created_at":"2021-01-26T20:26:20+00:00","updated_at":"2021-01-26T20:26:29+00:00","order_create_time":null,"customer_email":"","title":"Computer Case","order_id":null,"comment":null,"customer_name":"Computer Case","archived":false,"original_country":"","itemTimeLength":null,"stayTimeLength":1,"service_code":null,"status_info":null,"origin_info":{"ReferenceNumber":null,"ItemReceived":null,"ItemDispatched":null,"DepartfromAirport":null,"ArrivalfromAbroad":null,"CustomsClearance":null,"DestinationArrived":null,"weblink":"https://www.ups.com/us/en/Home.page","phone":null,"carrier_code":"ups","trackinfo":[{"Date":"2021-01-26 10:28","StatusDescription":"Shipper created a label, UPS has not received the package yet.","Details":"US","ActType":"M","substatus_num":11,"substatus":"notfound001","checkpoint_status":"transit"}]},"destination_info":{"ItemReceived":null,"ItemDispatched":null,"DepartfromAirport":null,"ArrivalfromAbroad":null,"CustomsClearance":null,"DestinationArrived":null,"weblink":null,"phone":null,"carrier_code":null,"trackinfo":null},"lastEvent":"Shipper created a label, UPS has not received the package yet.,US,2021-01-26 10:28","lastUpdateTime":"2021-01-26 10:28"}

**Comment by martinkooij** [comment]
Hi Mike, 
I hate these half-documented API's. But hey, they're free ;). . I am struggling with the time stamps. 

Three packages were created at 1/26/2021, between 20:26-20:46 in GMT time zone (would be 1:26-1:46PM in MST?).  These are indicated in the main body. This fits with package 1 where 13:.44 is mentioned (without TZ indication, could be MST). However package 2 and 3 are stamped at 10:xx which (cross checking with the "entered time" would mean GMT-10, which is the middle of the Pacific (Hawaii?)). Especially the trackinginfo timestamp on package 2 is weird., some 15 minutes off. 

Do you have some more timestamp info from the ups tracking app itself? I don't have a solid pattern yet. 

Martin

P.S. I long for the aftership API with all timestamps TZ-ed. I did some email exchange, and they promised would "revise" their commercial API offerings by the end of January, but I have no control over what they will do and whether there will be a free tier again. I begged for it :).

**Comment by MikeBishop** [comment]
Package 0 shows it was created on 1/26 at 1:44 PM in Plainfield, IN (so EST); all other timestamps in the app for that package are after the dump I provided.

Package 1 was created 1/26 at 10:28 AM in Baldwin Park, CA (so PST), then marked In Transit at 10:33 AM.

Package 2 was created 1/26 at 10:28 AM, also in Baldwin Park, CA.

**Pull request merged**
